version: '3.0'
services:
  session_nosql_service:
    image: redis:3.2.10
    container_name: session_nosql
    command: redis-server
    ports:
      - 5268:6379
    networks:
      - hnet

networks:
  hnet:
    driver: bridge